import { ContentItem, Subject, Source } from "./types";

export const SUBJECTS: Subject[] = [
  { id: "all",       label: "All subjects",  icon: "📚" },
  { id: "science",   label: "Science",       icon: "🔬" },
  { id: "math",      label: "Mathematics",   icon: "📐" },
  { id: "history",   label: "History",       icon: "🏛️" },
  { id: "coding",    label: "Coding",        icon: "💻" },
  { id: "language",  label: "English",       icon: "📝" },
  { id: "geography", label: "Geography",     icon: "🌍" },
  { id: "civics",    label: "Civics",        icon: "⚖️" },
  { id: "exam",      label: "Exam Prep",     icon: "🎯" },
];

export const SOURCES: Source[] = [
  { name: "YouTube EDU", icon: "▶", category: "Videos",   url: "https://youtube.com/education" },
  { name: "Khan Academy", icon: "🎓", category: "Courses", url: "https://khanacademy.org" },
  { name: "Wikipedia",   icon: "📖", category: "Articles", url: "https://wikipedia.org" },
  { name: "NCERT",       icon: "📗", category: "Textbooks",url: "https://ncert.nic.in" },
  { name: "Coursera",    icon: "🏅", category: "Courses",  url: "https://coursera.org" },
];

export const MOCK_CONTENT: ContentItem[] = [
  {
    id: "1",
    title: "Human Body Systems — Complete Overview",
    description: "Detailed walkthrough of digestive, nervous, and circulatory systems with animations and real examples.",
    source: "YouTube EDU", sourceIcon: "▶",
    type: "video", subject: "science",
    url: "https://youtube.com", duration: "22 min",
    level: "Beginner", featured: true,
  },
  {
    id: "2",
    title: "Algebra Fundamentals",
    description: "Variables, equations, and functions built from the ground up. Includes 40+ practice problems.",
    source: "Khan Academy", sourceIcon: "🎓",
    type: "course", subject: "math",
    url: "https://khanacademy.org", duration: "3 hrs",
    level: "Beginner", featured: true,
  },
  {
    id: "3",
    title: "Indian Independence Movement",
    description: "Key events, leaders, and turning points — 1857 to 1947. Written for Class 8–12 students.",
    source: "Wikipedia", sourceIcon: "📖",
    type: "article", subject: "history",
    url: "https://en.wikipedia.org/wiki/Indian_independence_movement",
    level: "Intermediate",
  },
  {
    id: "4",
    title: "Python for Beginners",
    description: "Write your first program, master loops, functions, and data structures in 4 weeks.",
    source: "Coursera", sourceIcon: "🏅",
    type: "course", subject: "coding",
    url: "https://coursera.org", duration: "4 weeks",
    level: "Beginner", featured: true,
  },
  {
    id: "5",
    title: "JEE Mains — Physics Full Prep",
    description: "Chapter-wise notes, formulas and 200+ practice questions. Mechanics, Optics, Thermodynamics.",
    source: "NCERT", sourceIcon: "📗",
    type: "exam", subject: "exam",
    url: "https://ncert.nic.in", level: "Advanced",
  },
  {
    id: "6",
    title: "Climate Change & India",
    description: "What causes it, what is changing, and what it means for Indian agriculture, coasts, and cities.",
    source: "YouTube EDU", sourceIcon: "▶",
    type: "video", subject: "science",
    url: "https://youtube.com", duration: "18 min",
    level: "Intermediate",
  },
  {
    id: "7",
    title: "English Grammar — Tenses & Usage",
    description: "All 12 tenses explained with examples, common mistakes, and practice exercises.",
    source: "Khan Academy", sourceIcon: "🎓",
    type: "course", subject: "language",
    url: "https://khanacademy.org", duration: "2 hrs",
    level: "Beginner",
  },
  {
    id: "8",
    title: "Class 10 Geometry — NCERT Solved",
    description: "Triangles, circles, and constructions with fully solved NCERT examples and extra questions.",
    source: "NCERT", sourceIcon: "📗",
    type: "textbook", subject: "math",
    url: "https://ncert.nic.in", level: "Intermediate",
  },
  {
    id: "9",
    title: "How the Internet Works",
    description: "HTML, HTTP, DNS, browsers — a visual, plain-language introduction for absolute beginners.",
    source: "YouTube EDU", sourceIcon: "▶",
    type: "video", subject: "coding",
    url: "https://youtube.com", duration: "15 min",
    level: "Beginner",
  },
  {
    id: "10",
    title: "The Constitution of India",
    description: "Fundamental rights, directive principles, branches of government — simplified for students.",
    source: "Wikipedia", sourceIcon: "📖",
    type: "article", subject: "civics",
    url: "https://en.wikipedia.org/wiki/Constitution_of_India",
    level: "Intermediate",
  },
  {
    id: "11",
    title: "Physical Geography of India",
    description: "Rivers, mountain ranges, plains, and climate zones — with maps and key facts for board exams.",
    source: "NCERT", sourceIcon: "📗",
    type: "textbook", subject: "geography",
    url: "https://ncert.nic.in", level: "Beginner",
  },
  {
    id: "12",
    title: "UPSC Prelims — General Studies",
    description: "Comprehensive notes covering polity, history, economy and environment for UPSC aspirants.",
    source: "YouTube EDU", sourceIcon: "▶",
    type: "exam", subject: "exam",
    url: "https://youtube.com", duration: "Series",
    level: "Advanced",
  },
];
